--- Interface
-- @module rethinkdb.reql
-- @author Adam Grandquist
-- @license Apache
-- @copyright Adam Grandquist 2016

local m = {}

function m.init(r)
  --- Helper to determine type of public interface.
  -- Returns a string from the following list or nil.
  -- - connection: returned from r.connector().connect or r.connect
  -- - connector: returned from r.connector
  -- - cursor: returned from query.run
  -- - error: an error generated by the driver or server.
  -- - reql: returned from r.reql...
  -- All of these objects are determined by duck typing. They have a property r
  -- that points to the driver they were created with. The driver created
  -- instances also have meta tables that at least provide a nice string
  -- representation for logging.
  function r.type(obj)
    if type(obj) ~= 'table' then return nil end
    if not getmetatable(obj) then return nil end
    if type(obj.r) ~= 'table' then return nil end

    if type(obj.run) == 'function' then
      return 'reql'
    end

    if type(obj._start) == 'function' and type(obj.use) == 'function' then
      if type(obj.noreply_wait) == 'function' then
        return 'connection'
      end

      return 'connector'
    end

    if type(obj.each) == 'function' and type(obj.to_array) == 'function' then
      return 'cursor'
    end

    if obj.ReQLError then
      return 'error'
    end

    return nil
  end
end

return m
