return {
    AbstractEntityIndex = require("entitas.entitas.AbstractEntityIndex"),
    Collector = require("entitas.entitas.Collector"),
    Context = require("entitas.entitas.Context"),
    Delegate = require("entitas.entitas.Delegate"),
    Entity = require("entitas.entitas.Entity"),
    EntityIndex = require("entitas.entitas.EntityIndex"),
    Group = require("entitas.entitas.Group"),
    GroupEvent = require("entitas.entitas.GroupEvent"),
    MakeComponent = require("entitas.entitas.MakeComponent"),
    Matcher = require("entitas.entitas.Matcher"),
    PrimaryEntityIndex = require("entitas.entitas.PrimaryEntityIndex"),
    Systems = require("entitas.entitas.Systems"),
    ReactiveSystem = require("entitas.entitas.ReactiveSystem"),
}